version: "2.3"
services:
  quora_scraping:
    build: ./
    environment:
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017
      - MONGO_USER=root
      - MONGO_PASS=Techno1419Techno
      - MONGO_DBNAME=quora_data
      - QUORA_EMAIL=samiatechnometrics@gmail.com
      - QUORA_PASS=UWXqd#LyWMy3A2@
    volumes:
      - ./REPORT:/app/REPORT
      - ./ERROR:/app/ERROR
    restart: always